# Generated by Django 3.2.12 on 2022-06-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0002_auto_20220605_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_id',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
