# Generated by Django 3.2.12 on 2022-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0003_auto_20220607_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='recipient',
        ),
        migrations.AddField(
            model_name='announcement',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
