# Generated by Django 3.2.12 on 2022-06-14 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0004_auto_20220610_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='notificationTitle',
            new_name='notification_title',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='formDate',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='notificationDescription',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='toDate',
        ),
        migrations.AddField(
            model_name='announcement',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='can_buy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notification_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='point_to_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cleanaddisAPI.report'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='point_to_waste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cleanaddisAPI.waste'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
